version: "3.9"
services:
  db:
    image: postgis/postgis
    ports:
      - "54320:5432"
    environment:
      POSTGRES_PASSWORD: dev
    volumes:
      - db_speed_test_data:/var/lib/postgresql/data
    deploy:
      # Do not touch the memory limits or TX will destroy you
      resources:
        limits:
          memory: 8g
        reservations:
          memory: 4g
    shm_size: '8gb'

volumes:
  db_speed_test_data:
    external: true

 
